# Generated by Django 5.2.1 on 2025-06-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='designinfo',
            new_name='orderinfo',
        ),
    ]
