# Generated by Django 5.2.1 on 2025-06-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_designinfo_userrequest_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
